use project;

insert into Address (AddressId, Street, City, State, Country) values (1, 'Sherman', 'Al Bāţinah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (2, 'Dovetail', 'Al Matūn', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (3, 'Sloan', 'Ar Rawḑ', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (4, 'Westport', 'Dhī Nā‘im', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (5, 'Dawn', '‘Amd', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (6, 'Springview', 'Al Matūn', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (7, 'Hansons', 'Bāqim as Sūq', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (8, 'Stoughton', 'Maqbanah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (9, 'Annamark', 'Ḩabūr', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (10, 'Meadow Vale', '‘Ubāl', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (11, 'Ilene', 'Yufrus', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (12, 'Shoshone', '‘Amrān', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (13, 'Corben', 'Ar Rawḑ', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (14, 'Morningstar', 'Grytviken', null, 'South Georgia and the South Sandwich Islands');
insert into Address (AddressId, Street, City, State, Country) values (15, 'Mifflin', 'Al Khirāb', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (16, 'Trailsway', 'Madīnat Lab‘ūs', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (17, 'Tennessee', 'Māwiyah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (18, 'Golf Course', 'Al ‘Anān', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (19, 'Schurz', 'Al Bāţinah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (20, 'Waubesa', 'Shiḩan as Suflá', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (21, 'Buena Vista', 'Al ‘Aqabah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (22, 'Westridge', 'Al Mukallā', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (23, 'Florence', '‘Amrān', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (24, 'Hollow Ridge', 'Al Ḩashwah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (25, 'Hansons', 'Sayḩūt', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (26, 'Farmco', 'Shiḩan as Suflá', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (27, 'Anhalt', 'Burūm', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (28, 'Trailsway', 'Judaydah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (29, 'Esker', 'Maţarah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (30, 'Carey', 'Ash Shiḩr', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (31, 'Hallows', 'Ash Sharyah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (32, 'Warrior', 'Qaryat al Qābil', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (33, 'Ridgeview', 'Markaz Mudhaykirah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (34, 'Marquette', 'Mawza‘', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (35, 'Graedel', 'Maswarah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (36, 'East', 'Suḩayl Shibām', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (37, 'Prairieview', 'Al Maḩwīt', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (38, 'Linden', 'Jiblah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (39, 'Sheridan', 'Saḩab', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (40, 'Fuller', 'Majzar', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (41, 'Katie', 'Sayyān', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (42, 'Loomis', 'Al Ma‘allā’', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (43, 'Russell', 'Kushar', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (44, 'Glendale', 'Al Wuday‘', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (45, 'Onsgard', 'Dhī as Sufāl', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (46, 'Stoughton', 'At Tawāhī', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (47, 'Bartillon', 'Al ‘Anān', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (48, 'Manitowish', 'Rumāh', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (49, 'Havey', 'Grytviken', null, 'South Georgia and the South Sandwich Islands');
insert into Address (AddressId, Street, City, State, Country) values (50, 'Harbort', 'Suḩayl Shibām', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (51, 'Scoville', 'As Suwaydā', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (52, 'Chive', 'Bi’r Ḩāt', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (53, 'Elmside', 'Qa‘ţabah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (54, 'Morning', 'Al ‘Ashshah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (55, 'Mccormick', 'Āl Ma‘ūdah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (56, 'Hallows', 'Dhamār', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (57, 'Crescent Oaks', 'Al Qurayshīyah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (58, 'Browning', 'Bāqim as Sūq', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (59, 'Crowley', 'Mawza‘', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (60, 'Twin Pines', 'Al Ḩashwah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (61, 'Golf View', 'Al Qurayshīyah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (62, 'Mitchell', 'Maţarah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (63, 'Nancy', 'Şuwayr', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (64, 'Roth', 'Dhalie', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (65, 'Warner', 'Mabyan', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (66, 'Atwood', 'Al Khirāb', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (67, 'Browning', 'Bayt ‘Adhāqah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (68, 'Melrose', 'Al ‘Anān', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (69, 'Blaine', 'Najd al Jumā‘ī', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (70, 'East', 'Ḩammām Damt', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (71, 'Union', 'Bi’r Ḩāt', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (72, 'Pond', 'Al Khāniq', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (73, 'Green Ridge', 'Ma‘bar', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (74, 'Alpine', 'Kushar', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (75, 'Marquette', 'Kushar', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (76, 'Mcguire', 'Zakhim', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (77, 'Center', 'Tarīm', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (78, 'Hermina', 'Az̧ Z̧alī‘ah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (79, 'Roth', 'Ar Rawnah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (80, 'Moose', 'Shiḩan as Suflá', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (81, 'Butternut', 'Al Khawkhah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (82, 'Almo', 'Ad Dimnah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (83, 'Canary', 'Qaryat al Qābil', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (84, 'Carpenter', 'Ar Rubū‘', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (85, 'Hudson', 'Dhī Nā‘im', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (86, 'Helena', 'Dhahi', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (87, 'Morningstar', 'Jiblah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (88, 'Russell', 'Lawdar', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (89, 'Sunnyside', 'Al Maḩwīt', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (90, 'Arrowood', 'Shiḩan as Suflá', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (91, 'Di Loreto', 'As Sayyānī', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (92, 'Melby', 'Ḩabābah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (93, 'Namekagon', 'Shiḩan as Suflá', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (94, 'Merchant', 'Shiḩan as Suflá', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (95, 'Marquette', 'Sūq Şirwāḩ', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (96, 'Del Sol', 'Al Ḩarf', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (97, 'Amoth', 'Al Misrākh', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (98, 'Gina', 'Sāh', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (99, 'Mallory', 'Āl Ma‘ūdah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (100, 'Summer Ridge', 'Sūq Sibāḩ', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (101, 'Karstens', 'Ar Rawḑ', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (102, 'Old Gate', 'Qaryat al Qābil', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (103, 'Mccormick', 'Markaz Mudhaykirah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (104, 'Di Loreto', 'Mayfa‘ah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (105, 'Holmberg', 'Ad Dimnah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (106, 'Lillian', 'Al Bāţinah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (107, 'Charing Cross', 'Yufrus', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (108, 'Northfield', 'Tarīm', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (109, 'Sauthoff', 'Az̧ Z̧alī‘ah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (110, 'Loeprich', 'Dhī as Sufāl', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (111, 'Artisan', 'Ḩajjah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (112, 'Bluejay', 'At Tawāhī', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (113, 'Rowland', 'Al ‘Aqabah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (114, 'Forest', 'Laḩij', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (115, 'Ludington', 'Ḩawf', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (116, 'Spohn', 'Ash Shuqayrah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (117, 'Claremont', 'Maţarah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (118, 'Forest', 'Suḩayl Shibām', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (119, 'Fairview', 'As Sayyānī', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (120, 'Elgar', 'Maqbanah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (121, 'Mallory', 'Zakhim', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (122, '6th', 'Matnah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (123, 'Tennyson', 'Sayḩūt', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (124, 'Cardinal', 'Al Misrākh', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (125, 'Cascade', 'Sūq ar Rabū‘', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (126, 'Blaine', 'Dhī Nā‘im', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (127, 'Hudson', 'Bayt ‘Adhāqah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (128, 'Sherman', 'Ḩajjah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (129, 'Declaration', 'Maqbanah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (130, 'Corben', 'Şanā’', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (131, 'Meadow Valley', 'Ad Dimnah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (132, 'Mandrake', '‘Abs', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (133, 'Basil', '‘Amrān', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (134, 'Bartillon', 'Ḩabīl al Jabr', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (135, 'Laurel', 'Aş Şalw', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (136, 'Susan', 'Ḩabīl ar Raydah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (137, 'Marquette', 'Yarīm', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (138, 'Lawn', 'Rajūzah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (139, 'Spohn', '‘Amrān', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (140, 'Melvin', 'Al Miftāḩ', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (141, 'South', 'Maţarah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (142, 'Ohio', 'Lawdar', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (143, 'Kensington', 'Ma‘bar', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (144, 'Johnson', 'Ḑubāh', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (145, 'Bonner', 'Al Jarrāḩī', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (146, 'Melody', 'Al Maşlūb', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (147, 'Browning', '‘Abs', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (148, 'Emmet', 'Al Maḩjal', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (149, 'Arrowood', 'Al ‘Āqir', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (150, 'Reindahl', 'Al Ḩashwah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (151, 'Stone Corner', 'Al Ḩumaydāt', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (152, 'Homewood', 'Āl Ma‘ūdah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (153, 'Blaine', 'Al Ḩudaydah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (154, 'Springs', 'Ad Dann', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (155, 'Moulton', 'Al ‘Āqir', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (156, 'Corben', 'Al Wuday‘', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (157, 'Vermont', 'Madīnat Lab‘ūs', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (158, 'Merry', 'Al Khawkhah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (159, 'Pine View', 'Ḑawrān ad Daydah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (160, 'Corscot', 'Al Bilād', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (161, 'Garrison', 'Bi’r Ḩāt', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (162, 'Lakewood', 'Al ‘Anān', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (163, 'Derek', 'Ḩabīl al Jabr', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (164, 'Colorado', 'Manwakh', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (165, 'Bunker Hill', 'Ar Rubū‘', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (166, 'Fieldstone', 'Al ‘Anān', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (167, 'Sunfield', 'Shiḩan as Suflá', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (168, 'Ronald Regan', 'Al Mashāf', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (169, 'Nobel', 'Markaz Mudhaykirah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (170, 'Reindahl', 'At Taḩālif', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (171, 'Logan', 'At Taḩālif', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (172, 'Summit', 'Bayḩān', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (173, 'Anniversary', '‘Abs', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (174, 'Lillian', 'Ḩammām Damt', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (175, 'Debra', 'Zakhim', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (176, 'Warner', 'Al Maḩjal', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (177, 'Linden', 'Al Munīrah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (178, 'Stoughton', 'Matnah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (179, 'Mccormick', 'Markaz Bilād aţ Ţa‘ām', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (180, 'Waywood', 'Al Maḩfid', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (181, 'Meadow Valley', 'Aţ Ţawīlah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (182, '1st', 'Mabyan', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (183, 'Comanche', 'Şuwayr', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (184, 'Arkansas', 'Al Qanāwiş', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (185, 'Fordem', 'Raydah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (186, 'Dryden', 'Al Ghayl', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (187, 'Mallard', 'Al Bilād', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (188, 'Lunder', 'Al Hijrah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (189, 'Grim', 'Al Ḩashwah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (190, 'Stoughton', 'Raydah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (191, 'Sage', 'Yarīm', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (192, 'Green Ridge', 'Al Hijrah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (193, 'Eagan', 'Al Mukallā', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (194, 'Elmside', 'Markaz al Marīr', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (195, 'Knutson', 'Laḩij', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (196, 'Ridge Oak', 'Sāqayn', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (197, 'Annamark', 'Al Nashmah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (198, 'Moland', 'Al Qurayshīyah', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (199, 'Starling', 'Ash Shawātī', null, 'Yemen');
insert into Address (AddressId, Street, City, State, Country) values (200, 'Linden', 'Al Ḩashwah', null, 'Yemen');
