use project;
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (1, 4, 'Heavy Duty Power Drill Set', 513, 34);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (2, 121, 'Professional Gardening Tool Kit', 411, 41);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (3, 79, 'Stylish Denim Jeans', 75, 29);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (4, 222, 'Organic Fruit Basket', 734, 67);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (5, 76, 'Elegant Diamond Stud Earrings ', 144, 29);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (6, 51, 'Durable Camping Backpack', 574, 46);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (7, 248, 'High-Fidelity Wireless Speaker', 750, 32);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (8, 7, 'Professional Gardening Tool Kit', 997, 30);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (9, 149, 'Professional Gardening Tool Kit', 878, 28);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (10, 68, 'Smartphone Charging Dock', 190, 31);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (11, 222, 'Durable Camping Backpack', 170, 78);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (12, 71, 'Fitness Tracker Watch', 649, 12);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (13, 177, 'Fitness Tracker Watch', 204, 91);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (14, 149, 'Heavy Duty Power Drill Set', 376, 26);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (15, 245, 'Computers', 353, 50);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (16, 233, 'Elegant Diamond Stud Earrings ', 83, 96);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (17, 142, 'Premium Tennis Racket', 231, 58);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (18, 27, 'Heavy Duty Power Drill Set', 989, 95);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (19, 16, 'Organic Fruit Basket', 699, 44);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (20, 138, 'Soft Baby Blanket Set', 762, 81);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (21, 33, 'Premium Tennis Racket', 538, 3);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (22, 178, 'Games', 946, 52);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (23, 223, 'Car Cleaning Kit', 566, 35);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (24, 80, 'Computers', 374, 39);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (25, 56, 'Classic Leather Sneakers', 267, 94);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (26, 255, 'Educational Puzzle Set', 488, 19);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (27, 296, 'Natural Skincare Gift Set', 954, 18);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (28, 60, 'Heavy Duty Work Gloves', 764, 64);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (29, 116, 'Educational Puzzle Set', 147, 98);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (30, 69, 'Natural Skincare Gift Set', 862, 73);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (31, 85, 'Computers', 5, 45);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (32, 46, 'High-Fidelity Wireless Speaker', 989, 96);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (33, 194, 'Books', 849, 83);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (34, 291, 'Organic Fruit Basket', 750, 73);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (35, 171, 'Soft Baby Blanket Set', 402, 50);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (36, 291, 'Cozy Throw Blanket', 386, 97);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (37, 83, 'Toys', 612, 92);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (38, 258, 'Durable Camping Backpack', 773, 31);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (39, 65, 'High-Fidelity Wireless Speaker', 712, 19);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (40, 52, 'Games', 546, 93);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (41, 191, 'Books', 7, 15);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (42, 123, 'Stylish Denim Jeans', 555, 94);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (43, 207, 'Stylish Denim Jeans', 695, 84);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (44, 211, 'Soft Baby Blanket Set', 523, 2);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (45, 201, 'Professional Gardening Tool Kit', 531, 25);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (46, 266, 'Stylish Denim Jeans', 656, 56);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (47, 206, 'Books', 909, 47);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (48, 175, 'Natural Skincare Gift Set', 465, 47);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (49, 110, 'Smartphone Charging Dock', 891, 84);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (50, 205, 'Educational Puzzle Set', 44, 36);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (51, 63, 'Car Cleaning Kit', 841, 94);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (52, 48, 'Organic Fruit Basket', 395, 42);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (53, 146, 'Smartphone Charging Dock', 957, 13);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (54, 234, 'Heavy Duty Work Gloves', 7, 31);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (55, 140, 'Fitness Tracker Watch', 363, 24);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (56, 69, 'Durable Camping Backpack', 420, 94);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (57, 95, 'Educational Puzzle Set', 549, 44);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (58, 219, 'Games', 390, 28);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (59, 199, 'Classic Leather Sneakers', 210, 37);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (60, 86, 'Cozy Throw Blanket', 632, 99);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (61, 100, 'Professional Gardening Tool Kit', 153, 97);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (62, 52, 'Heavy Duty Work Gloves', 70, 60);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (63, 191, 'Books', 802, 38);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (64, 29, 'High-Fidelity Wireless Speaker', 680, 45);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (65, 29, 'Classic Movie Box Set', 501, 30);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (66, 77, 'Smartphone Charging Dock', 30, 93);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (67, 7, 'Heavy Duty Power Drill Set', 796, 61);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (68, 192, 'Heavy Duty Work Gloves', 983, 32);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (69, 64, 'Fitness Tracker Watch', 245, 92);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (70, 219, 'Natural Skincare Gift Set', 92, 89);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (71, 8, 'Computers', 940, 22);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (72, 271, 'Cozy Throw Blanket', 947, 44);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (73, 115, 'Classic Leather Sneakers', 381, 22);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (74, 138, 'Car Cleaning Kit', 877, 7);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (75, 186, 'Games', 425, 79);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (76, 137, 'Classic Leather Sneakers', 8, 95);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (77, 29, 'Car Cleaning Kit', 510, 41);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (78, 243, 'Durable Camping Backpack', 589, 92);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (79, 10, 'Stylish Denim Jeans', 73, 7);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (80, 33, 'Natural Skincare Gift Set', 901, 65);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (81, 168, 'Fitness Tracker Watch', 957, 30);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (82, 181, 'Car Cleaning Kit', 2, 36);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (83, 283, 'Elegant Diamond Stud Earrings ', 800, 35);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (84, 118, 'Heavy Duty Work Gloves', 460, 41);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (85, 112, 'Organic Fruit Basket', 859, 35);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (86, 53, 'Toys', 372, 39);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (87, 60, 'Organic Fruit Basket', 894, 37);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (88, 127, 'Fitness Tracker Watch', 100, 39);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (89, 34, 'Heavy Duty Work Gloves', 928, 46);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (90, 53, 'Cozy Throw Blanket', 798, 7);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (91, 214, 'Smartphone Charging Dock', 407, 27);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (92, 69, 'Toys', 421, 24);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (93, 138, 'Classic Leather Sneakers', 151, 26);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (94, 251, 'Classic Leather Sneakers', 219, 92);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (95, 288, 'Organic Fruit Basket', 41, 44);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (96, 61, 'Classic Leather Sneakers', 506, 39);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (97, 147, 'Stylish Denim Jeans', 849, 21);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (98, 217, 'Toys', 385, 86);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (99, 277, 'Educational Puzzle Set', 733, 92);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (100, 227, 'Educational Puzzle Set', 524, 56);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (101, 263, 'Professional Gardening Tool Kit', 63, 42);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (102, 228, 'Classic Leather Sneakers', 809, 34);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (103, 159, 'Toys', 455, 69);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (104, 109, 'Books', 938, 27);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (105, 281, 'Heavy Duty Power Drill Set', 361, 78);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (106, 224, 'Classic Movie Box Set', 238, 1);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (107, 206, 'Car Cleaning Kit', 419, 3);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (108, 219, 'Games', 800, 92);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (109, 228, 'Premium Tennis Racket', 250, 95);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (110, 295, 'Soft Baby Blanket Set', 925, 96);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (111, 205, 'Cozy Throw Blanket', 934, 31);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (112, 248, 'Classic Movie Box Set', 891, 77);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (113, 63, 'Heavy Duty Work Gloves', 873, 40);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (114, 141, 'Soft Baby Blanket Set', 358, 15);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (115, 286, 'Soft Baby Blanket Set', 682, 55);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (116, 24, 'Heavy Duty Power Drill Set', 210, 3);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (117, 32, 'Car Cleaning Kit', 596, 25);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (118, 186, 'Fitness Tracker Watch', 46, 18);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (119, 163, 'Cozy Throw Blanket', 706, 70);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (120, 194, 'Durable Camping Backpack', 830, 63);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (121, 172, 'Premium Tennis Racket', 838, 77);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (122, 286, 'Heavy Duty Power Drill Set', 427, 97);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (123, 214, 'Computers', 307, 7);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (124, 173, 'Smartphone Charging Dock', 985, 84);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (125, 235, 'Games', 173, 70);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (126, 202, 'Premium Tennis Racket', 689, 43);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (127, 101, 'Elegant Diamond Stud Earrings ', 890, 71);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (128, 15, 'Books', 168, 37);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (129, 45, 'Durable Camping Backpack', 632, 17);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (130, 257, 'Heavy Duty Power Drill Set', 867, 91);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (131, 16, 'Classic Movie Box Set', 954, 14);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (132, 1, 'Organic Fruit Basket', 977, 85);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (133, 102, 'Classic Leather Sneakers', 478, 42);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (134, 234, 'Stylish Denim Jeans', 361, 88);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (135, 88, 'Soft Baby Blanket Set', 833, 63);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (136, 122, 'Natural Skincare Gift Set', 428, 81);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (137, 262, 'Games', 2, 62);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (138, 71, 'Heavy Duty Work Gloves', 333, 100);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (139, 198, 'Soft Baby Blanket Set', 414, 84);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (140, 286, 'Premium Tennis Racket', 295, 64);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (141, 158, 'Classic Movie Box Set', 65, 29);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (142, 120, 'Natural Skincare Gift Set', 648, 21);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (143, 150, 'Smartphone Charging Dock', 516, 61);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (144, 110, 'Car Cleaning Kit', 855, 73);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (145, 80, 'Premium Tennis Racket', 595, 57);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (146, 131, 'Smartphone Charging Dock', 612, 77);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (147, 99, 'Heavy Duty Work Gloves', 617, 95);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (148, 165, 'Games', 135, 53);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (149, 193, 'Heavy Duty Power Drill Set', 312, 55);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (150, 163, 'Natural Skincare Gift Set', 904, 93);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (151, 105, 'Games', 542, 44);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (152, 126, 'Cozy Throw Blanket', 614, 27);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (153, 37, 'Books', 641, 86);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (154, 187, 'Cozy Throw Blanket', 820, 32);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (155, 188, 'Computers', 443, 29);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (156, 11, 'Classic Leather Sneakers', 86, 38);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (157, 8, 'Classic Movie Box Set', 332, 29);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (158, 287, 'Classic Movie Box Set', 388, 90);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (159, 151, 'Fitness Tracker Watch', 740, 73);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (160, 88, 'Organic Fruit Basket', 155, 65);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (161, 229, 'Soft Baby Blanket Set', 966, 50);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (162, 258, 'Premium Tennis Racket', 750, 73);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (163, 174, 'Toys', 393, 26);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (164, 208, 'Heavy Duty Work Gloves', 832, 17);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (165, 5, 'Heavy Duty Power Drill Set', 760, 44);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (166, 212, 'Cozy Throw Blanket', 590, 38);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (167, 182, 'Heavy Duty Work Gloves', 300, 75);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (168, 144, 'Stylish Denim Jeans', 595, 82);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (169, 142, 'Cozy Throw Blanket', 478, 39);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (170, 149, 'Car Cleaning Kit', 309, 44);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (171, 8, 'High-Fidelity Wireless Speaker', 693, 5);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (172, 18, 'Books', 150, 57);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (173, 231, 'Smartphone Charging Dock', 382, 85);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (174, 149, 'Computers', 848, 79);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (175, 273, 'Educational Puzzle Set', 150, 20);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (176, 99, 'Fitness Tracker Watch', 294, 75);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (177, 196, 'Soft Baby Blanket Set', 753, 76);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (178, 61, 'Heavy Duty Work Gloves', 366, 62);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (179, 175, 'Organic Fruit Basket', 522, 8);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (180, 9, 'Stylish Denim Jeans', 538, 61);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (181, 32, 'Games', 35, 8);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (182, 72, 'High-Fidelity Wireless Speaker', 239, 11);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (183, 265, 'Classic Movie Box Set', 363, 17);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (184, 141, 'Smartphone Charging Dock', 103, 28);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (185, 110, 'Fitness Tracker Watch', 727, 6);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (186, 57, 'Car Cleaning Kit', 886, 35);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (187, 11, 'Heavy Duty Power Drill Set', 306, 17);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (188, 150, 'Smartphone Charging Dock', 598, 35);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (189, 150, 'Toys', 579, 14);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (190, 43, 'High-Fidelity Wireless Speaker', 52, 86);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (191, 171, 'Organic Fruit Basket', 156, 74);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (192, 93, 'Stylish Denim Jeans', 865, 19);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (193, 135, 'Soft Baby Blanket Set', 137, 90);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (194, 101, 'Books', 621, 49);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (195, 41, 'Soft Baby Blanket Set', 774, 18);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (196, 156, 'Durable Camping Backpack', 557, 46);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (197, 160, 'Stylish Denim Jeans', 774, 88);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (198, 75, 'Games', 705, 34);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (199, 271, 'Durable Camping Backpack', 882, 91);
insert into Product (ProductID, SupplierID, Name, Price, Quantity) values (200, 184, 'Durable Camping Backpack', 417, 82);
